include: package:flutter_lints/flutter.yaml

# Additional rules and customizations can be added here
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true