name: Flutter Web Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Java (required by Flutter)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Verify Flutter installation
      run: flutter --version
      
    - name: Install dependencies
      working-directory: Phase1_Landing_v1.0/apps/phase1_flutter
      run: flutter pub get
      
    - name: Analyze code
      working-directory: Phase1_Landing_v1.0/apps/phase1_flutter
      run: flutter analyze
      
    - name: Run tests
      working-directory: Phase1_Landing_v1.0/apps/phase1_flutter
      run: flutter test
      
    - name: Build Flutter web (release)
      working-directory: Phase1_Landing_v1.0/apps/phase1_flutter
      run: flutter build web --release
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: Phase1_Landing_v1.0/apps/phase1_flutter/build/web/